services:
  nestjs-boilerplate-api:
    image: nestjs-boilerplate-api-local
    container_name: nestjs-boilerplate-api-local
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - nestjs-boilerplate-mongodb
      - redis
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    networks:
      - nestjs-boilerplate-network

  nestjs-boilerplate-mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_USER_PASSWORD}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - mongo_data:/data/db
    networks:
      - nestjs-boilerplate-network

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    environment:
      REDIS_ARGS: "--requirepass redispass"
    volumes:
      - redis_data:/data
    networks:
      - nestjs-boilerplate-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - nestjs-boilerplate-network

volumes:
  mongo_data:
  redis_data:

networks:
  nestjs-boilerplate-network:
    driver: bridge
